"""Created review and unlocked_items tables, small updates to others

Revision ID: 6b6f280c9853
Revises: 0a1f8c087402
Create Date: 2025-08-11 16:26:24.105904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6f280c9853'
down_revision: Union[str, Sequence[str], None] = '0a1f8c087402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('SONG', 'ALBUM', 'ARTIST', name='reviewtype'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=1), nullable=False),
    sa.Column('review_text', sa.String(length=1000), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_item_id'), 'reviews', ['item_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('unlocked_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('SONG', 'ALBUM', 'ARTIST', name='reviewtype'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id', name='unique_user_item')
    )
    op.create_index(op.f('ix_unlocked_items_item_id'), 'unlocked_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_unlocked_items_user_id'), 'unlocked_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unlocked_items_user_id'), table_name='unlocked_items')
    op.drop_index(op.f('ix_unlocked_items_item_id'), table_name='unlocked_items')
    op.drop_table('unlocked_items')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_item_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
