"""Added release_date field to song model

Revision ID: 7c36ce64505e
Revises: 6d81819a43d7
Create Date: 2025-08-18 17:28:48.573604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c36ce64505e'
down_revision: Union[str, Sequence[str], None] = '6d81819a43d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('release_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_songs_release_date'), 'songs', ['release_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_release_date'), table_name='songs')
    op.drop_column('songs', 'release_date')
    # ### end Alembic commands ###
