"""Final changes to db for MVP

Revision ID: b596fc1d8e4d
Revises: 7c36ce64505e
Create Date: 2025-08-18 18:10:44.669353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b596fc1d8e4d'
down_revision: Union[str, Sequence[str], None] = '7c36ce64505e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_review_user_item', 'reviews', ['user_id', 'song_id', 'album_id', 'artist_id'], unique=False)
    op.add_column('token_transactions', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.create_index('idx_token_trans_idempotency', 'token_transactions', ['idempotency_key', 'user_id'], unique=False)
    op.create_index(op.f('ix_token_transactions_idempotency_key'), 'token_transactions', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_transactions_idempotency_key'), table_name='token_transactions')
    op.drop_index('idx_token_trans_idempotency', table_name='token_transactions')
    op.drop_column('token_transactions', 'idempotency_key')
    op.drop_index('idx_review_user_item', table_name='reviews')
    # ### end Alembic commands ###
